dist: bionic
language: java

services:
- docker

jdk:
- openjdk11

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_HOST=unix:///var/run/docker.sock

install: true # no need to call 'mvn install'

jobs:
  include:
  - script: mvn verify -B -e -DcreateJavadoc=true -DCI=$CI -Pbuild-docker-image,run-tests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    name: "file based registry"
  - script: mvn verify -B -e -DcreateJavadoc=true -DCI=$CI -Pbuild-docker-image,run-tests,device-registry-mongodb -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    name: "MongoDB based registry"
  - script: mvn verify -B -e -DCI=$CI -Pbuild-docker-image,run-tests,device-registry-jdbc -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    name: "JDBC based registry"
