# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

name: ci

on:
  pull_request:

jobs:

  build-chart:
    runs-on: ubuntu-latest
    needs: check-for-chart-changes
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml -am -pl org.eclipse.hono:hono-deploy
      - run: mv deploy/target/eclipse-hono-*-chart.tar.gz eclipse-hono-chart.tar.gz
      - name: Upload helm chart
        uses: actions/upload-artifact@v1
        with:
          name: helm-chart
          path: eclipse-hono-chart.tar.gz

  lint-chart:
    runs-on: ubuntu-latest
    needs: build-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download packages helm chart
        uses: actions/download-artifact@v1
        with:
          name: helm-chart
      - run: mkdir -p charts
      - run: cd charts && tar xzf ../eclipse-hono-chart.tar.gz --strip-components 2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@master
        with:
          command: lint
          config: /home/runner/work/hono/hono/.github/helm-lint.yaml
